polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'

urlpatterns = [
	path('main/', views.login, name='login'),
	path('main/login', views.signIn, name='signIn'),
	path('main/signup', views.signUp, name='signUp'),
	path('main/logout', views.logout, name='logout'),

	path('', views.index, name='index'),
	path('add/', views.addQuestion, name='addQuestion'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
	path('<int:question_id>/vote', views.vote, name='vote'),

]
xurlpatterns = [
	path("", views.index, name='index'),

	# ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),

    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),

    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /polls/string/x
    path('<str:name>/x/', views.info, name="info"),

]

readwisefree/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.db import models

# Create your models here.

class User(models.Model):
	name = models.CharField(max_length=40)
	password = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Question(models.Model): #extended Model
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published') 
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	# user = models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.choice_text


class Vote(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	choice = models.ForeignKey(Choice,on_delete=models.CASCADE)
	# votes = models.IntegerField(default=0)

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, User, Vote, Choice
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'


    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def index(request):
    if 'user' in request.session:
        current_user = request.session['user']
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        context = {
            'latest_question_list': latest_question_list,
            'current_user' : current_user,
        }
        return render(request, 'polls/index.html', context)
    else:
        return render(request, 'polls/main.html')
	

	


def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choice = question.choice_set.get(pk=request.POST['choice'])
    # choice = get_object_or_404(Choice, pk=request.POST['choice'])
    user = User.objects.filter(username=request.session['user'])[0]

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        vote = Vote(question=question, choice=choice, user=user)
        vote.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def info(request, name):
	return HttpResponse("Your name is %s" % name) 

def addQuestion(request):

    question_text = (request.POST['question_text'])

    choice1 = request.POST['choice1']
    choice2 = request.POST['choice2']
    choice3 = request.POST['choice3']
    choice4 = request.POST['choice4']

    user = request.session['user']

    if not user:
        user = User.objects.get(pk=1)
    else:
        user = User.objects.filter(name=user)[0]

    
    try:
        question = Question(question_text= question_text, pub_date = timezone.now(), user = user)
        question.save()
        question.choice_set.create(choice_text=choice1, votes=0)
        question.choice_set.create(choice_text=choice2, votes=0)
        question.choice_set.create(choice_text=choice3, votes=0)
        question.choice_set.create(choice_text=choice4, votes=0)
    except Exception as e:
        raise
    else:
        
        return HttpResponse(question.id)

    


def login(request):
    return render(request, 'polls/main.html')

def signIn(request):

    username = request.POST['username']
    password = request.POST['pass']
    try:
        user = User.objects.filter(name=username, password=password)
    except Exception as e:
        raise
    else:
        if user:
            request.session['user'] = username
            return redirect('polls:index')
        else:
            return HttpResponse('username or password is errorjj')

    

def signUp(request):
    username = request.POST['username']
    password = request.POST['pass']
    try:
        user = User(name=username,password=password)
    except Exception as e:
        raise
    else:
        user.save();
        return HttpResponse(user.name + 'crearted succesfully created')

def logout(request):
    del request.session['user']
    return redirect('polls:login') #with message

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id%}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<!-- if already voted then show selected choice, and option for change your vote.. -->
<!-- {{ question.id }} -->
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<div>
    <div>
        Hi {{ user }} 
    </div>
    <div display="float">
        <a href="{% url 'polls:logout' %}">logout</a>
    </div>
</div>


<h3>Create a question </h3>

<form action="{% url 'polls:addQuestion' %}" method="post">
    {% csrf_token %}
    <input type="text" name="question_text">
    <br>
    <p>Otipons</p>
    <input type="text" name="choice1"> <br>
    <input type="text" name="choice2"> <br>
    <input type="text" name="choice3"> <br>
    <input type="text" name="choice4"> <br>

    <input type="submit" name="submit" value="Ask">
</form>



{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/main.html
<a href="{% url 'polls:signIn' %}">ok </a>

<form action="{% url 'polls:signIn' %}" method="post">
    {% csrf_token %}
    <label for="username">
        Username
    </label>
    <input type="text" name="username">

    <label for="pass">
        Password
    </label>
    <input type="text" name="pass">
   
    <input type="submit" name="submit" value="login">
</form>




<form action="{% url 'polls:signUp' %}" method="post">
    {% csrf_token %}
    <label for="Username">
        Username
    </label>
    <input type="text" name="username">

    <label for="pass">
        Password
    </label>
    <input type="text" name="pass">
   
    <input type="submit" name="submit" value="signup">
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>